name: secrets

on: 
  # push
  # schedule:
  #   - cron: "5 4 * * *"
  workflow_dispatch: 

env:
    CONTAINER_REGISTRY: docker.io
    
    IMAGE_NAME: github-actions
jobs:
   
    # docker:
    #     runs-on: ubuntu-latest
    #     steps:
    #     - name: Docker Build
    #       run: docker build -t docker.io/navya403/imageName:latest

    #     - name: Docker login
    #       run: docker login --username=navya403 --password=Navya@5566

    #     - name: Docker Publish
    #       run: docker push docker.io/navya403/imageName:latest
       

    # deploy:
    #     needs: docker
    #     runs-on: ubuntu-latest
    #     steps:
        
    #     - name: Docker run
    #       run: docker run -d -p 8080:80 docker.io/navya403/imageName:latest
    docker:
        
        runs-on: ubuntu-latest
        steps:
        - name: Docker Build
         
          run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

        - name: Docker login
          env:
            DOCKER_PASSWORD: Navya@5566
            
          run: echo docker login --username=$DOCKER_USERNAME --password=${{ secrets.DOCKER_PASSWORD}}

        - name: Docker Publish
          
          run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
       

    deploy:
       
        needs: docker
        runs-on: ubuntu-latest
        steps:
        
        - name: Docker run
       
          run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest